org: leucippus03
service: bookory-backend

provider:
  name: aws
  runtime: python3.12
  region: eu-north-1
  httpApi:
    cors: true

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
